### ISSUE TITLE
avoid useless installs

### ISSUE THREAD

**Issue by olesenm** [FoamScience/openfoam-apptainer-packaging#2]
Seen here:
https://github.com/FoamScience/openfoam-apptainer-packaging/blob/762d5bf344b86f1f39f77d21d314ca049f2ef8e2/basic/com-openfoam.def#L25

It would make much more sense to just install the openfoam-dev package (no tutorials!) instead of openfoam-default and then manually removing the tutorials!

**Comment by FoamScience** [comment]
Couldn't be more right. I must have had a specific reason why I stuck to the default package; but cannot remember now so not important.
