### ISSUE TITLE
use openfoam bash wrappers

### ISSUE THREAD

**Issue by olesenm** [FoamScience/openfoam-apptainer-packaging#3]
https://github.com/FoamScience/openfoam-apptainer-packaging/blob/762d5bf344b86f1f39f77d21d314ca049f2ef8e2/basic/com-openfoam.def#L47

But we actually provide and install bash wrappers as /usr/bin/openfoam2406,  /usr/bin/openfoam2312, etc.
I think it makes more sense to use those directly.

**Comment by FoamScience** [comment]
Originally, I wanted to keep all definition files similar so users don't face any differences in the environment,or the way they run their cases. But this seams to have minimal impact so we adopt the wrappers. Thanks!
